<?php

namespace Tests\Services\Parsers\Builders;

use App\Models\Admin\CatalogAttribute;
use App\Services\Parsers\Builders\AttributeBuild;
use App\Services\Parsers\Builders\CategoryBuild;
use Tests\TestCase;

class AttributeBuildTest extends TestCase
{
    /**
     * @var CategoryBuild|\Illuminate\Contracts\Foundation\Application|mixed
     */
    private $builder;
    /**
     * @var CatalogAttribute|\Illuminate\Contracts\Foundation\Application|mixed
     */
    private $catalogAttribute;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->builder = app(AttributeBuild::class);
        $this->catalogAttribute = app(CatalogAttribute::class);
    }

    public function testGetId()
    {
        $id = $this->builder->setFields([
            'title' => 'undfindet'
        ])->getId();

        $this->assertTrue(($id == null));

    }


    public function testGetIdInsert()
    {
        $title = 'Тест атрибут';

//        $this->catalogAttribute::where('title', $title)->delete();

        $id = $this->builder->setFields([
            'title' => $title
        ])->getIdInsertOrUpdate();

        $this->assertIsNumeric($id);
    }
}
