<?php

namespace Tests\Services\Parsers\Sites\Darvish;

use App\Services\Parsers\Sites\Darvish\LoadDarvish;
use App\Services\Parsers\Sites\Darvish\Templates\CategoryLvlOneTemplate;
use App\Services\Parsers\Sites\Darvish\Templates\ProductTemplate;
use Tests\TestCase;

class LoadDarvishTest extends TestCase
{
//    use RefreshDatabase;
//    use CreatesApplication;
    /**
     * @var LoadDarvish
     */
    private $parser;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->parser = new LoadDarvish();
    }

    public function test_load_start()
    {
        $this->parser->setType(CategoryLvlOneTemplate::class);
        $result = $this->parser->load('https://darvish.by/katalog/igrushki_i__tvorchestvo/');

        dump($result);

        $this->assertTrue(isset($result['url']));
    }

    public function test_load_before_last_category()
    {
        $this->parser->setType(CategoryLvlOneTemplate::class);
        $result = $this->parser->load('https://darvish.by/katalog/igrushki_i__tvorchestvo/',[
            'previous' => 'Сюжетно-ролевые игры',
            'from_lvl_one_url' => 'https://darvish.by/katalog/igrushki_i__tvorchestvo/'
        ]);

        $this->assertTrue($result['data']['previous'] == 'Хранение игрушек');
    }

    public function test_load_last_category()
    {
        $this->parser->setType(CategoryLvlOneTemplate::class);
        $result = $this->parser->load('https://darvish.by/katalog/igrushki_i__tvorchestvo/',[
            'previous' => 'Хранение игрушек',
            'from_lvl_one_url' => 'https://darvish.by/katalog/igrushki_i__tvorchestvo/'
        ]);

        $this->assertTrue(empty($result));
    }

    public function test_load_product()
    {
        $this->parser->setType(ProductTemplate::class);
        $this->parser->load('https://darvish.by/katalog/igrushki_i__tvorchestvo/aktivnye_igry/00034324/');

        $this->assertTrue(true);
    }
}
